from elasticsearch import Elasticsearch, helpers

# Connect to Elasticsearch
es = Elasticsearch(
    ["https://localhost:9200"],
    basic_auth=("elastic", "your_password"), 
    verify_certs=False
)

# Sample documents
docs = [

{"_index": "new_index", "_id": 1, "_source": {"name": "Alice", "age": 23, "city": "Dhaka", "date_of_birth": "2002-04-12"}},
{"_index": "new_index", "_id": 2, "_source": {"name": "Bob", "age": 30, "city": "Chattogram", "date_of_birth": "1995-08-25"}},
{"_index": "new_index", "_id": 3, "_source": {"name": "Charlie", "age": 28, "city": "Sylhet", "date_of_birth": "1997-03-09"}},
{"_index": "new_index", "_id": 4, "_source": {"name": "Diana", "age": 35, "city": "Khulna", "date_of_birth": "1990-06-17"}},
{"_index": "new_index", "_id": 5, "_source": {"name": "Ethan", "age": 26, "city": "Rajshahi", "date_of_birth": "1999-01-11"}},
{"_index": "new_index", "_id": 6, "_source": {"name": "Fiona", "age": 24, "city": "Barishal", "date_of_birth": "2001-10-05"}},
{"_index": "new_index", "_id": 7, "_source": {"name": "George", "age": 32, "city": "Dhaka", "date_of_birth": "1993-09-14"}},
{"_index": "new_index", "_id": 8, "_source": {"name": "Hannah", "age": 27, "city": "Mymensingh", "date_of_birth": "1998-02-18"}},
{"_index": "new_index", "_id": 9, "_source": {"name": "Ian", "age": 22, "city": "Rangpur", "date_of_birth": "2003-07-28"}},
{"_index": "new_index", "_id": 10, "_source": {"name": "Julia", "age": 29, "city": "Dhaka", "date_of_birth": "1996-12-04"}},
{"_index": "new_index", "_id": 11, "_source": {"name": "Kevin", "age": 31, "city": "Chattogram", "date_of_birth": "1994-05-23"}},
{"_index": "new_index", "_id": 12, "_source": {"name": "Laura", "age": 25, "city": "Sylhet", "date_of_birth": "2000-09-30"}},
{"_index": "new_index", "_id": 13, "_source": {"name": "Michael", "age": 33, "city": "Khulna", "date_of_birth": "1992-02-12"}},
{"_index": "new_index", "_id": 14, "_source": {"name": "Nora", "age": 27, "city": "Rajshahi", "date_of_birth": "1998-11-19"}},
{"_index": "new_index", "_id": 15, "_source": {"name": "Oscar", "age": 21, "city": "Barishal", "date_of_birth": "2004-03-22"}},
{"_index": "new_index", "_id": 16, "_source": {"name": "Paula", "age": 34, "city": "Dhaka", "date_of_birth": "1991-06-09"}},
{"_index": "new_index", "_id": 17, "_source": {"name": "Quentin", "age": 28, "city": "Chattogram", "date_of_birth": "1997-10-16"}},
{"_index": "new_index", "_id": 18, "_source": {"name": "Rachel", "age": 26, "city": "Sylhet", "date_of_birth": "1999-08-07"}},
{"_index": "new_index", "_id": 19, "_source": {"name": "Sam", "age": 25, "city": "Khulna", "date_of_birth": "2000-01-13"}},
{"_index": "new_index", "_id": 20, "_source": {"name": "Tina", "age": 22, "city": "Rajshahi", "date_of_birth": "2003-04-20"}},
{"_index": "new_index", "_id": 21, "_source": {"name": "Uma", "age": 30, "city": "Mymensingh", "date_of_birth": "1995-09-02"}},
{"_index": "new_index", "_id": 22, "_source": {"name": "Victor", "age": 27, "city": "Rangpur", "date_of_birth": "1998-05-15"}},
{"_index": "new_index", "_id": 23, "_source": {"name": "Wendy", "age": 33, "city": "Dhaka", "date_of_birth": "1992-07-08"}},
{"_index": "new_index", "_id": 24, "_source": {"name": "Xavier", "age": 29, "city": "Chattogram", "date_of_birth": "1996-02-27"}},
{"_index": "new_index", "_id": 25, "_source": {"name": "Yara", "age": 31, "city": "Sylhet", "date_of_birth": "1994-12-10"}},
{"_index": "new_index", "_id": 26, "_source": {"name": "Zane", "age": 23, "city": "Khulna", "date_of_birth": "2002-06-03"}},
{"_index": "new_index", "_id": 27, "_source": {"name": "Arif", "age": 29, "city": "Rajshahi", "date_of_birth": "1996-05-17"}},
{"_index": "new_index", "_id": 28, "_source": {"name": "Bela", "age": 24, "city": "Barishal", "date_of_birth": "2001-07-29"}},
{"_index": "new_index", "_id": 29, "_source": {"name": "Chinmoy", "age": 27, "city": "Mymensingh", "date_of_birth": "1998-10-14"}},
{"_index": "new_index", "_id": 30, "_source": {"name": "Dipa", "age": 33, "city": "Rangpur", "date_of_birth": "1992-01-06"}},
{"_index": "new_index", "_id": 31, "_source": {"name": "Elina", "age": 28, "city": "Dhaka", "date_of_birth": "1997-02-22"}},
{"_index": "new_index", "_id": 32, "_source": {"name": "Farhan", "age": 25, "city": "Chattogram", "date_of_birth": "2000-11-12"}},
{"_index": "new_index", "_id": 33, "_source": {"name": "Gita", "age": 26, "city": "Sylhet", "date_of_birth": "1999-03-30"}},
{"_index": "new_index", "_id": 34, "_source": {"name": "Habib", "age": 34, "city": "Khulna", "date_of_birth": "1991-08-19"}},
{"_index": "new_index", "_id": 35, "_source": {"name": "Ishita", "age": 23, "city": "Rajshahi", "date_of_birth": "2002-09-15"}},
{"_index": "new_index", "_id": 36, "_source": {"name": "Jamal", "age": 28, "city": "Barishal", "date_of_birth": "1997-06-25"}},
{"_index": "new_index", "_id": 37, "_source": {"name": "Kamal", "age": 31, "city": "Mymensingh", "date_of_birth": "1994-03-07"}},
{"_index": "new_index", "_id": 38, "_source": {"name": "Lina", "age": 29, "city": "Rangpur", "date_of_birth": "1996-10-11"}},
{"_index": "new_index", "_id": 39, "_source": {"name": "Mina", "age": 27, "city": "Dhaka", "date_of_birth": "1998-04-28"}},
{"_index": "new_index", "_id": 40, "_source": {"name": "Naim", "age": 22, "city": "Chattogram", "date_of_birth": "2003-05-21"}},
{"_index": "new_index", "_id": 41, "_source": {"name": "Omar", "age": 26, "city": "Sylhet", "date_of_birth": "1999-08-16"}},
{"_index": "new_index", "_id": 42, "_source": {"name": "Pari", "age": 30, "city": "Khulna", "date_of_birth": "1995-01-09"}},
{"_index": "new_index", "_id": 43, "_source": {"name": "Qadir", "age": 33, "city": "Rajshahi", "date_of_birth": "1992-09-18"}},
{"_index": "new_index", "_id": 44, "_source": {"name": "Rafi", "age": 21, "city": "Barishal", "date_of_birth": "2004-07-05"}},
{"_index": "new_index", "_id": 45, "_source": {"name": "Samiha", "age": 24, "city": "Mymensingh", "date_of_birth": "2001-12-02"}},
{"_index": "new_index", "_id": 46, "_source": {"name": "Tanvir", "age": 29, "city": "Rangpur", "date_of_birth": "1996-03-13"}},
{"_index": "new_index", "_id": 47, "_source": {"name": "Urmi", "age": 25, "city": "Dhaka", "date_of_birth": "2000-02-19"}},
{"_index": "new_index", "_id": 48, "_source": {"name": "Vikram", "age": 27, "city": "Chattogram", "date_of_birth": "1998-05-30"}},
{"_index": "new_index", "_id": 49, "_source": {"name": "Wasim", "age": 31, "city": "Sylhet", "date_of_birth": "1994-09-01"}},
{"_index": "new_index", "_id": 50, "_source": {"name": "Xenia", "age": 23, "city": "Khulna", "date_of_birth": "2002-07-17"}},
{"_index": "new_index", "_id": 51, "_source": {"name": "Yusuf", "age": 34, "city": "Rajshahi", "date_of_birth": "1991-12-25"}},
{"_index": "new_index", "_id": 52, "_source": {"name": "Zara", "age": 22, "city": "Barishal", "date_of_birth": "2003-10-08"}},
{"_index": "new_index", "_id": 53, "_source": {"name": "Anika", "age": 26, "city": "Mymensingh", "date_of_birth": "1999-09-03"}},
{"_index": "new_index", "_id": 54, "_source": {"name": "Bilal", "age": 28, "city": "Rangpur", "date_of_birth": "1997-06-12"}},
{"_index": "new_index", "_id": 55, "_source": {"name": "Cynthia", "age": 33, "city": "Dhaka", "date_of_birth": "1992-02-08"}},
{"_index": "new_index", "_id": 56, "_source": {"name": "Dipto", "age": 21, "city": "Chattogram", "date_of_birth": "2004-05-10"}},
{"_index": "new_index", "_id": 57, "_source": {"name": "Esha", "age": 24, "city": "Sylhet", "date_of_birth": "2001-11-04"}},
{"_index": "new_index", "_id": 58, "_source": {"name": "Faisal", "age": 29, "city": "Khulna", "date_of_birth": "1996-09-25"}},
{"_index": "new_index", "_id": 59, "_source": {"name": "Gulshan", "age": 27, "city": "Rajshahi", "date_of_birth": "1998-12-30"}},
{"_index": "new_index", "_id": 60, "_source": {"name": "Habiba", "age": 25, "city": "Barishal", "date_of_birth": "2000-06-22"}},
{"_index": "new_index", "_id": 61, "_source": {"name": "Imran", "age": 33, "city": "Mymensingh", "date_of_birth": "1992-04-03"}},
{"_index": "new_index", "_id": 62, "_source": {"name": "Joya", "age": 26, "city": "Rangpur", "date_of_birth": "1999-07-07"}},
{"_index": "new_index", "_id": 63, "_source": {"name": "Kamrul", "age": 22, "city": "Dhaka", "date_of_birth": "2003-11-27"}},
{"_index": "new_index", "_id": 64, "_source": {"name": "Lamia", "age": 31, "city": "Chattogram", "date_of_birth": "1994-01-15"}},
{"_index": "new_index", "_id": 65, "_source": {"name": "Morshed", "age": 28, "city": "Sylhet", "date_of_birth": "1997-09-20"}},
{"_index": "new_index", "_id": 66, "_source": {"name": "Nabila", "age": 23, "city": "Khulna", "date_of_birth": "2002-03-26"}},
{"_index": "new_index", "_id": 67, "_source": {"name": "Ovi", "age": 30, "city": "Rajshahi", "date_of_birth": "1995-12-16"}},
{"_index": "new_index", "_id": 68, "_source": {"name": "Pavel", "age": 24, "city": "Barishal", "date_of_birth": "2001-05-28"}},
{"_index": "new_index", "_id": 69, "_source": {"name": "Raisa", "age": 27, "city": "Mymensingh", "date_of_birth": "1998-02-02"}},
{"_index": "new_index", "_id": 70, "_source": {"name": "Shuvo", "age": 25, "city": "Rangpur", "date_of_birth": "2000-09-14"}},
{"_index": "new_index", "_id": 71, "_source": {"name": "Tanisha", "age": 29, "city": "Dhaka", "date_of_birth": "1996-07-01"}},
{"_index": "new_index", "_id": 72, "_source": {"name": "Uzzal", "age": 26, "city": "Chattogram", "date_of_birth": "1999-03-04"}},
{"_index": "new_index", "_id": 73, "_source": {"name": "Vania", "age": 33, "city": "Sylhet", "date_of_birth": "1992-10-19"}},
{"_index": "new_index", "_id": 74, "_source": {"name": "Wasif", "age": 31, "city": "Khulna", "date_of_birth": "1994-11-13"}},
{"_index": "new_index", "_id": 75, "_source": {"name": "Xahid", "age": 22, "city": "Rajshahi", "date_of_birth": "2003-08-11"}},
{"_index": "new_index", "_id": 76, "_source": {"name": "Yasmin", "age": 34, "city": "Barishal", "date_of_birth": "1991-04-10"}},
{"_index": "new_index", "_id": 77, "_source": {"name": "Zahid", "age": 27, "city": "Mymensingh", "date_of_birth": "1998-06-01"}},
{"_index": "new_index", "_id": 78, "_source": {"name": "Amin", "age": 25, "city": "Rangpur", "date_of_birth": "2000-05-02"}},
{"_index": "new_index", "_id": 79, "_source": {"name": "Bithi", "age": 28, "city": "Dhaka", "date_of_birth": "1997-08-23"}},
{"_index": "new_index", "_id": 80, "_source": {"name": "Chanchal", "age": 29, "city": "Chattogram", "date_of_birth": "1996-09-05"}},
{"_index": "new_index", "_id": 81, "_source": {"name": "Dipika", "age": 33, "city": "Sylhet", "date_of_birth": "1992-12-15"}},
{"_index": "new_index", "_id": 82, "_source": {"name": "Emon", "age": 21, "city": "Khulna", "date_of_birth": "2004-01-26"}},
{"_index": "new_index", "_id": 83, "_source": {"name": "Farzana", "age": 23, "city": "Rajshahi", "date_of_birth": "2002-07-30"}},
{"_index": "new_index", "_id": 84, "_source": {"name": "Gias", "age": 27, "city": "Barishal", "date_of_birth": "1998-10-17"}},
{"_index": "new_index", "_id": 85, "_source": {"name": "Hridoy", "age": 25, "city": "Mymensingh", "date_of_birth": "2000-02-11"}},
{"_index": "new_index", "_id": 86, "_source": {"name": "Imtiaz", "age": 29, "city": "Rangpur", "date_of_birth": "1996-06-13"}},
{"_index": "new_index", "_id": 87, "_source": {"name": "Jannat", "age": 26, "city": "Dhaka", "date_of_birth": "1999-04-07"}},
{"_index": "new_index", "_id": 88, "_source": {"name": "Kawsar", "age": 31, "city": "Chattogram", "date_of_birth": "1994-05-20"}},
{"_index": "new_index", "_id": 89, "_source": {"name": "Liton", "age": 28, "city": "Sylhet", "date_of_birth": "1997-09-18"}},
{"_index": "new_index", "_id": 90, "_source": {"name": "Monir", "age": 30, "city": "Khulna", "date_of_birth": "1995-03-23"}},
{"_index": "new_index", "_id": 91, "_source": {"name": "Nasrin", "age": 24, "city": "Rajshahi", "date_of_birth": "2001-06-30"}},
{"_index": "new_index", "_id": 92, "_source": {"name": "Omar Faruk", "age": 35, "city": "Barishal", "date_of_birth": "1990-10-08"}},
{"_index": "new_index", "_id": 93, "_source": {"name": "Parvez", "age": 23, "city": "Mymensingh", "date_of_birth": "2002-05-14"}},
{"_index": "new_index", "_id": 94, "_source": {"name": "Ritu", "age": 27, "city": "Rangpur", "date_of_birth": "1998-07-25"}},
{"_index": "new_index", "_id": 95, "_source": {"name": "Sajid", "age": 29, "city": "Dhaka", "date_of_birth": "1996-01-09"}},
{"_index": "new_index", "_id": 96, "_source": {"name": "Tania", "age": 26, "city": "Chattogram", "date_of_birth": "1999-03-28"}},
{"_index": "new_index", "_id": 97, "_source": {"name": "Umar", "age": 33, "city": "Sylhet", "date_of_birth": "1992-12-03"}},
{"_index": "new_index", "_id": 98, "_source": {"name": "Vishal", "age": 31, "city": "Khulna", "date_of_birth": "1994-11-21"}},
{"_index": "new_index", "_id": 99, "_source": {"name": "Wali", "age": 22, "city": "Rajshahi", "date_of_birth": "2003-09-29"}},
{"_index": "new_index", "_id": 100, "_source": {"name": "Zerin", "age": 25, "city": "Barishal", "date_of_birth": "2000-02-18"}}

]


# Bulk insert
helpers.bulk(es, docs)

# Print 
print("✅ Documents inserted successfully!")
